export const RazaValuesEx = [
    "Mestizo",
    "Afgano",
    "Airdale Terrier",
    "Akita",
    "Alaskan Malamute",
    "Angora",
    "Basset Hound",
    "Beagle",
    "Beagle/Basset",
    "Bichon Frise",
    "Boston Terrier",
    "Boxer",
    "Braco",
    "Breton Español",
    "Bull Terrier",
    "Bulldog",
    "Caniche",
    "Chihuahua",
    "Chow Chow",
    "Cocker American",
    "Cocker Ingles",
    "Cocker Spaniel",
    "Collie",
    "Dachshund",
    "Dalmata",
    "Doberman",
    "Dogo Argentino",
    "Drahthaar",
    "Fox Terrier",
    "Galgo",
    "Golden Retriever",
    "Gran Danes",
    "Gran Pirineo",
    "Himalaya",
    "Kerry Blue Terr",
    "Kuvasz",
    "Labrador Retriever",
    "Lhassa Apso",
    "Maltes",
    "Ovejero Aleman",
    "Pastor Belga",
    "Pastor Briard",
    "Pastor Canadien",
    "Pastor De Brie",
    "Pastor Escoces",
    "Pastor Ingles",
    "Pekines",
    "Pointer",
    "Pomerania",
    "Poodle Mediano",
    "Poodle Miniatur",
    "Poodle Toy",
    "Pug",
    "Puli",
    "Rottweiler",
    "Samoyedo",
    "San Bernardo",
    "Schnauzer",
    "Schnauzer Enano",
    "Schnauzer Gigant",
    "Schnauzer Median",
    "Scottish Terrier",
    "Selyham Terrier",
    "Setter Ingles",
    "Setter Irlandes",
    "Shar-Pei",
    "Shetland Sheepdo",
    "Shih-Tzu",
    "Siberian Husky",
    "Silky Terrier",
    "Skye Terrier",
    "Springel Spaniel",
    "Staffordshire",
    "Terrier",
    "Vizla",
    "Wair Hair",
    "Weimaraner",
    "Welsh Corgi",
    "Welsh Terrier",
    "West Highland",
    "Whippet",
    "Wire Fox Terrier",
    "Yorkshire Terrie"
]