export const AreaDetail = [
  'Abdomen',
  'Abdomen Lateral',
  'Abdomen Ventral',
  'Acantosis en las Axilas',
  'Almohadillas plantares',
  'Area de pliegues',
  'Area inguinal',
  'Area perilabial',
  'Area perilabial superior',
  'Area periocular',
  'Area periocular en forma de mariposa',
  'Area umbilical',
  'Areas de pelos más cortos',
  'Axilas',
  'Base de la Cola en forma triángular con vértice hacia craneal',
  'Borde orejas',
  'Cabeza',
  'Caderas',
  'Cara',
  'Cara interna',
  'Cara interna muslos',
  'Carpo',
  'Codos',
  'Cola',
  'Cola en el 1/3 superior Dorsal',
  'Conducto auditivo externo',
  'Conductos auditivos',
  'Craneal',
  'Cuello',
  'Dedos matriz de las uñas',
  'Dentro de la cavidad bucal',
  'Desde el area inguinal hasta las Axilas',
  'Distal de las extremidades',
  'Dorsal',
  'Escroto',
  'Espacios interdigitales',
  'Esternón',
  'Ginecomastía',
  'Hocico',
  'Ingles',
  'Interior del Pabellón auricular',
  'Labios inferiores',
  'Las venas mamarias son claramente visible',
  'Mentón',
  'Metacarpo',
  'Metatarsos',
  'Miembros',
  'Miembros en la Región Lateral',
  'Muslos(Cara externa)',
  'Muslos(Cara interna)',
  'Nariz',
  'No tiene un patrón Característico',
  'Orejas(Cara externa)',
  'Otitis',
  'Pabellón auricular',
  'Pabellón auricular(Cara externa)',
  'Pabellón auricular(Cara interna)',
  'Parches seborreicos',
  'Parcial orejas',
  'Parpado-conjuntiva',
  'Periné',
  'Pezones hiperpigmentados agrandados',
  'Pies',
  'Planum nasale',
  'Prepucio',
  'Puente nasal',
  'Punta de la Cola',
  'Puntos de presión',
  'Regiones con pelos más cortos',
  'Región esternal',
  'Región isquiática',
  'Región lumbo-sacra',
  'Región masetérica',
  'Región perianal',
  'Región poplítea',
  'Tarsos',
  'Tibias',
  'Toda la superficie corporal',
  'Todo el cuerpo',
  'Tórax',
  'Tórax Dorsal',
  'Tórax Lateral',
  'Tórax Ventral',
  'Uniones muco-cutáneas',
  'Uñas',
  'Vulva'
]