export const DiagnosticoDiferencialDetail = [
  'Prácticamente NO tiene',
  'Se realiza entre las patologías señaladas en la etiología',
  'Piodermia juvenil',
  'Dermatitis nasal solar',
  'Dermatofitosis con infección secundaria',
  'Lupus eritematosus sistémico o discoide',
  'Pénfigos',
  'Demodeccia',
  'Carencia de Zinc',
  'Dermatofitosis con infección bacteriana secundaria',
  'Candidiasis',
  'Demodeccia localizada',
  'Celulitis juvenil',
  'Dermatofitosis microsporica',
  'Neoplasias',
  'Cuerpos extraños',
  'Bursitis',
  'Hipersensibilidad bacteriana NO verdadera',
  'Foliculitis bacteriana',
  'Dermatofitosis por microsporum',
  'Dermatofitosis por Microsporum',
  'Sarna sarcóptica',
  'Urticaria',
  'Pénfigo foliaceo',
  'Lupus eritematoso',
  'Tiña microspórica',
  'Parches seborreicos',
  'Hipersensibilidad bacteriana verdadera',
  'Demodeccia generalizada',
  'Dermatofitosis generalizada',
  'Infección por mycobacterias atípicas',
  'Mycobacterias',
  'Micosis sistémicas y subcutáneas',
  'Enfermedades autoinmunes',
  'Neoplasia',
  'Traumas',
  'Lesión por contiguidad de los sacos anales',
  'Tumor de glándulas circunanales',
  'Atopía con la que puede coexistir',
  'Alergía alimentaria, con la que puede coexistir',
  'Piodermia superficial',
  'Hipersensibilidad a los parásitos intestinales',
  'Otras dermatitis seborreicas',
  'Alergia alimentaria',
  'Dermatitis alérgica por contacto',
  'Dermatitis alérgica a las pulgas',
  'Hipersensibilidad bacteriana',
  'Piodermia de superficie',
  'Dermatitis irritativa de contacto',
  'Atopía',
  'Todas las hipersensibilidades',
  'Todas las seborreas secundarias',
  'Piodérmia superficial',
  'Otras hipersensibilidades',
  'Seborreas primarias y secundarias',
  'Dermatitis alérgica de contacto',
  'Foliculitis bacterianas',
  'Otros tipos de pénfigos',
  'Lupus eritematoso sistémico',
  'Lupus discoideo',
  'Dermatitis que responde al Zinc',
  'Dermatofitosis',
  'Seborreas',
  'Síndrome hepatocutáneo',
  'Penfigoide bulloso',
  'Necrólisis epidérmica tóxica',
  'Estomatitis ulcerativa',
  'Pénfigo vulgar',
  'Erupción por fármacos',
  'Pénfigo vulgar,',
  'Lupus eritematoso discoideo',
  'Síndrome hepato-cutáneo',
  'Pénfigo eritematoso',
  'Pénfigo foliáceo',
  'Hiperqueratosis nasal',
  'Vitíligo',
  'Piodermia profunda',
  'Alergía alimentaria',
  'Dermatitis de contacto',
  'Dermatitis por Malassezia',
  'Dermatitis por otodectes',
  'Dermatitis por Cheyletiella',
  'Tiña tricofíticas con infección secundaria',
  'Pénfigo folíaceo y vulgaris',
  'ALOPECIA POR MUTACION DE COLOR',
  'CELULITIS JUVENIL',
  'DERMATITIS DE LOS PLIEGUES',
  'DERMATITIS POR MALASSEZIA',
  'DERMATOFITOSIS POR MICROSPORUM',
  'DERMATOFITOSIS POR TRICOFITON',
  'DERMATOMIOSITIS',
  'DERMATOSIS QUE RESPONDE AL ZINC-I',
  'DERMATOSIS QUE RESPONDE AL ZINC-II',
  'FOLICULITIS BACTERIANA',
  'FOLICULITIS BACTERIANA SUPERFICIAL',
  'FOLICULITIS Y FORUNCULOSIS DEL MENTON',
  'FOLICULITIS Y FORUNCULOSIS NASAL',
  'FOLICULITIS, FURUNCULOSIS Y CELULITIS',
  'HIPERSENSIBILIDAD BACTERIANA NO VERDADERA',
  'IMPETIGO',
  'LUPUS ERITEMATOSO SISTEMICO',
  'PIODERMIA DEL OVEJERO ALEMAN',
  'Dermatomiositis',
  'Dermatitis por cheyletiella',
  'Dermatitis por Mallazesia',
  'Sarna otodéctica',
  'Hiposomatotrofismo',
  'Hipotiroidismo',
  'Otros desbalances hormonales',
  'Hiperadrenocortisismo.Hiposomatotrofismo',
  'Con las otras dermatopatías hormonales',
  'Con dermatitis seborreicas idiopáticas',
  'Si hay mucho prurito con hipersensibilidades como atopía, hipersensibilidad hormonal, dermatitis alérgica de contacto',
  'Con el resto de las dermatopatías de origen hormonal',
  'Con las otras dermatopatías de origen hormonal, particularmente con el tumor de células de Sertoli',
  'Con las hipersensibilidades, particularmente la alimentaria y con atopía',
  'El más importante es con el síndrome de feminización o hipoandrogenismo con el que comparte la mayoría de los signos clínicos',
  'Hiperadrenocorticoidismo',
  'Con desbalance de las hormonas sexuales adrenales',
  'Hipersomatotrofismo',
  'Con hipersensibilidad bacteriana, éstas tienen la localización de las piodermias y además siempre tienen algún pelo en su interior',
  'Parches seborreicos, siempre hay pelos en su interior',
  'Mastocitomas',
  'Histiocitomas',
  'Neurodermatitis',
  'Parche caliente incipiente',
  'Pénfigo foliáceo y eritematoso',
  'Dermatitis pustular subcorneal',
  'Con otras micosis sistémicas como histoplasmosis, criptococcosis, blastomicosis, phaeohypomicosis y micetomas',
  'Fístulas crónicas',
  'Seborreas secundarias',
  'Displasia epidérmica',
  'Adenitis sebácea',
  'Distrofia folicular',
  'Comedones del Schnauzer',
  'ALOPECIA POR MUTACION DE COLOR',
  'DEMODECCIA LOCALIZADA',
  'DERMATITIS ALERGICA POR CONTACTO',
  'DERMATITIS ALERGICA POR PULGAS',
  'DERMATOFITOSIS POR MICROSPORUM',
  'DERMATOSIS POR HIPERESTROGENISMO',
  'HIPERSENSIBILIDAD BACTERIANA NO VERDADERA',
  'Fisuras de las orejas',
  'Picadura de la mosca de la punta de oreja',
  'Dermatofitosis microspórica',
  'Moquillo de las almohadillas plantares (Hard-pad Disease)',
  'Dermatosis que responden al Zinc',
  'Pénfigo foliáceo, lupus eritematoso sistémico',
  'Carencia de zinc',
  'Leishmaniasis',
  'Seborreas primarias o secundarias',
  'Dermatosis que responden al zinc',
  'Callos',
  'Piodermias',
  'Acantosis nigricans secundaria',
  'Se deben buscar entre las causas señaladas en la etiología',
  'Otras endocrinopatías',
  'Dermatitis seborreicas',
  'Callos de apoyo',
  'Granulomas micóticos',
  'Hipersensibilidades todas',
  'Hipersensibilidad a parásitos intestinales',
  'El de las etiologías',
  'Tumores de los sacos anales',
  'Hiperplasias glandulares',
  'Tumores de las glándulas perianales',
  'Fístulas perianales incipientes'
]