export const LesionDetail = [
  'Alopecía',
  'Alopecía parcial',
  'Bullas acantolíticas',
  'Calcinosis',
  'Cerúmen seco y oscuro',
  'Collaretes epidérmicos',
  'Collaretes epidérmicos pigmentados',
  'Costras',
  'Descamación',
  'Edema',
  'Eritema',
  'Eritema leve',
  'Forunculosis',
  'Hiperpigmentación',
  'Hiperqueratosis',
  'Pápulas',
  'Pústulas',
  'Pústulas estériles',
  'Piel delgada',
]